### PR TITLE
Consider the enums defined in messages

### PR DESCRIPTION
**Pull request by sbuliarca**

### CODE REVIEW

**Review by tosan88 — DISMISSED** [review]

**Comment by sbuliarca** [comment]
Tested it in this PR: https://github.com/utilitywarehouse/billing-engine-protobuf-model/pull/156/files

**Comment by rcrowe** [comment]
There was a reason this wasn't implemented, I'm going to try remembering & if I can't come back to you soonish to unblock.
This tool was ejected from a mono repo, so hoping I can find a discussion there.

**Review by rcrowe — CHANGES_REQUESTED** [review]
This leads to name clashes. I've used this branch on an internal repo & it generated invalid code.

```
enum Foo {
  UNKNOWN = 0;
}

message Schema {
  enum SomeType {
    UNKNOWN = 0;
  }
}
```

This will generate 2 top-level consts of `UNKNOWN`, which obviously doesn't compile.

**Comment by sbuliarca** [comment]
Hey @rcrowe ! I'll update this to detect collisions for nested enums & skip them if there are any.

**Review by tosan88 — DISMISSED** [review]

**Review by rcrowe — APPROVED** [review]

**Pull request merged**
